const notes = [];
function saveNote(content, id) {
    if (typeof content !== "string" || !(Number.isInteger(id)) || arguments.length !== 2) {
        console.log("Provide a valid input type");
        return;
    }
    if (exsistingId(id)) {
        console.log(`This id is already exsist so generating a new id for this content`);
        id = createId();
    }
    notes.push({ content: content, id: id });

}
const exsistingId = id => notes.find(element => element.id === id) === undefined ? false : true;

function createId() {
    const uniqueid = Math.floor(Date.now() * Math.random());
    return uniqueid;
}
saveNote("Pick up groceries", 1);
saveNote("Do laundry", 2);
saveNote("Library visit", 3);
saveNote("Evening-walk", 3);
saveNote(676, "hello");
saveNote("Sunday class", 4);
saveNote("Room Cleaning", 2);
console.log("My saved notes list");
console.log(notes);

function getNote(id) {
    if (typeof id != "number") {
        console.log(`Please provide a numerical value as id to fetch content`);
    }
    if (!exsistingId(id)) {
        console.log(`The id doesn't exist so fetching not possible`);
        return;
    }
    else
        return notes.find(element => element.id === id)
}

const firstNote = getNote(3);
const secondNote = getNote(7);
const thirdNote = getNote("hi");
const fourthtNote = getNote(4);
console.log(`Here is the list of get notes`);
console.log(firstNote);
console.log(fourthtNote);

function logOutNotesFormatted() {
    for (let element of notes) {
        console.log(`The note with id ${element['id']}, has the following note content: ${element['content']} `);
    }

}
logOutNotesFormatted();
//As an extra feature here I am trying to add 2 new attributes pin and catagory and on the basis of category
//we can pin those notes.

function pinnedNotes() {
    for (let element of notes) {
        element['pin'] = false;
        element['category'] = 'daily-work';
    }

}
pinnedNotes();
//let's add some more notes with different category and updates save function with those extra features to save
function saveNoteWithPin(content, id, pin, category) {
    if (typeof content !== "string" || !(Number.isInteger(id)) || arguments.length !== 4) {
        console.warn("Provide a valid input type");
        return;
    }
    if (exsistingId(id)) {
        console.log(`This id is already exsist so generating a new id for this content`);
        id = createId();
    }
    notes.push({ content: content, id: id, pin: pin, category: category });

}
saveNoteWithPin("DJ", 5, false, "entertainment");
saveNoteWithPin("Movie time", 6, false, "other");
saveNoteWithPin("Circus", 7, false, "entertainment");
saveNoteWithPin("Baking class", 8, false, "routine-work");
saveNoteWithPin("Friend visit", 9, false, "entertainment");
saveNoteWithPin("Friend visit", 10, false, "entertainment");
saveNoteWithPin("Friend visit", 11, false, "daily-work");
//callin a function which will pin those notes which fall in entertainment category
// function pinned(value) {
//     function check(element) {
//         let result = element['category'] === value;
//         return result;
//     }
//     let output = notes.filter(check);
//     return output
// }

//  with arrow function 
const pinned = value => notes.filter(element => element['category'] === value);
let newnotes = pinned("entertainment");
//set pin property to true value for those new notes values generated by filter
for (let element of newnotes) {
    element['pin'] = true;
}
console.log(`Here is the list of  notes with extra features "pinned"  whose category is entertainment `);
console.log(newnotes);

